project: 'bi-connector'
master_doc: 'index'
paths:
  static: ['source/.static']
theme:
  name: 'guides'
  sitename: 'MongoDB Connector for BI'
  jira: 'DOCS'
  google_analytics: 'UA-7301842-8'
  nav_excluded:
    - /
sidebars:
  '**':
    - 'localtoc.html'
...
